export const MENU_LIST_START = 'MENU_LIST_START';
export const MENU_LIST_SUCCESS = 'MENU_LIST_SUCCESS';
export const MENU_LIST_FAIL = 'MENU_LIST_FAIL';
export const MENU_ADD_REALTIME = 'MENU_ADD_REALTIME';
export const MENU_UPDATE_REALTIME = 'MENU_UPDATE_REALTIME';
export const MENU_DELETE_REALTIME = 'MENU_DELETE_REALTIME';